Feature/co 2183/automate v0 1
osu-mist/github-testing-automation pull request #1
Opened 2023-09-26 00:32 UTC by RanaTayyab

create version 0.1

2023-09-26 15:41 UTC, tsoliangwu0130 requested changes

2023-09-26 15:41 UTC, tsoliangwu0130 commented on README.md
> +# GitHub Automator
Let's call it GitHub Testing Automation for the consistency with the repo name.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on README.md
> +- Python 3.x (Used: 3.11)
Can you add a version badge to this README? Example: https://img.shields.io/badge/node-10.17-brightgreen.svg

2023-09-26 15:41 UTC, tsoliangwu0130 commented on README.md
> +- Access Token with the necessary permissions
Which permissions/scopes are required for this script?

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +import logging
This should be in alphabetical order.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +from github import Github
This should be in alphabetical order, and `github` is actually imported twice (although the second time is to import a module `Github` from `github`). I think these two lines should be able to combine into one.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +from typing import Dict, List
`List` is imported but never used.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +import github
`git` and `github` are not listed in `requirements.txt` and can't be resolved. Are they built-in in 3.11 or something?

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +
Per pep8 standard, we need 2 blank lines here.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +    def __init__(self, access_token: str, base_url: str, username: str, repo_name: str, repo_dir: str):
Line too long (> 79 characters).

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +        formatter = logging.Formatter('%(asctime)s [%(levelname)s] - %(message)s')
Line too long (> 79 characters). There are still some lines that violate this rule among your codes. I'm not going to point them out individually. Can you fix them all?

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +            self.logger.info(f'Repository {self.repo_name} already exists. Using the existing repository.')
I don't think you should throw an exception if the repo is already existed. Instead, you should use an if-else section to handle this logic.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +        if repo_local:  # Only proceed if repo_local has been initialized
Since you have already had an try-except above to ensure `repo_local` is initialized, do you still need to check again here?

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +                self.logger.info('Initial commit pushed to main branch.')
I guess these lines should be moved into `commit_and_push` function (you might want to adjust that function to make it reusable for different use cases) and this function should only focus on the testing of creating and initializing repo.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +        REPO_DIR = credentials.get('repo_dir', '')
What's the main purpose of assigning default empty values to these credentials? Shouldn't we directly stop the script if there is any missed?

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +        time.sleep(2)
Just curious, what are we waiting for here?

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +    main()
Missing a line break EOF.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +
Expected 2 blank lines here.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +
Expected 2 blank lines here.

2023-09-26 15:41 UTC, tsoliangwu0130 commented on automate.py
> +    def delete_repos_with_automation(self) -> None:
Hmm, it's interesting. I'm not sure do we want to delete the testing repo after testing. It's been helpful for me to keep some testing repos so that we can dig into the root cause if we find anything is broken, but I can also understand why you want to delete them. What do you think?

2023-09-26 16:06 UTC, stacybrock commented on automate.py
> +import github
`git` is GitPython, and `github` is PyGithub.

2023-09-26 16:43 UTC, stacybrock commented on automate.py
> +from github import Github
In addition to @tsoliangwu0130's comments, per PEP 8, imports should be listed alphabetically and also broken into separate groups, like so:
```
import logging
import os
import time
import yaml
from typing import Dict, List

import git
import github
from github import Github
```

Grouping imports this way makes it a lot easier to see at a glance what kind of libraries are being used.

See: https://peps.python.org/pep-0008/#imports

I'm leaving the question regarding if `import github` and `from github import Github` should be combined into one statement up to @RanaTayyab to figure out. 😁

2023-09-26 16:46 UTC, tsoliangwu0130 commented on automate.py
> +from github import Github
@stacybrock yep. Just for your reference, we also have some customized style guilds which were built based on pep8 and flake8: https://github.com/osu-mist/style-guides/blob/master/Python.md

2023-09-27 15:49 UTC, RanaTayyab commented on README.md
> +# GitHub Automator
done.

2023-09-27 15:51 UTC, RanaTayyab commented on README.md
> +- Python 3.x (Used: 3.11)
done.

2023-09-27 15:51 UTC, RanaTayyab commented on README.md
> +- Access Token with the necessary permissions
defined permissions in ReadMe for token

2023-09-27 15:52 UTC, RanaTayyab commented on automate.py
> +import logging
done.

2023-09-27 15:52 UTC, RanaTayyab commented on automate.py
> +from github import Github
done.

2023-09-27 15:52 UTC, RanaTayyab commented on automate.py
> +from typing import Dict, List
fixed.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +
done.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +    def __init__(self, access_token: str, base_url: str, username: str, repo_name: str, repo_dir: str):
done.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +        formatter = logging.Formatter('%(asctime)s [%(levelname)s] - %(message)s')
done.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +            self.logger.info(f'Repository {self.repo_name} already exists. Using the existing repository.')
done.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +        if repo_local:  # Only proceed if repo_local has been initialized
done.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +        REPO_DIR = credentials.get('repo_dir', '')
done.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +        time.sleep(2)
it was for testing purposes, removed.

2023-09-27 15:53 UTC, RanaTayyab commented on automate.py
> +    main()
done.

2023-09-27 15:54 UTC, RanaTayyab commented on automate.py
> +
done.

2023-09-27 15:54 UTC, RanaTayyab commented on automate.py
> +
done.

2023-09-27 15:55 UTC, RanaTayyab commented on automate.py
> +    def delete_repos_with_automation(self) -> None:
while testing, it can create lots of repos, this is just a cleanup function by one run, and I don't call it in the main function for final deployment. Just for dev testing.

2023-09-27 15:55 UTC, RanaTayyab commented on automate.py
> +from github import Github
fixed :)

2023-09-27 15:56 UTC, RanaTayyab commented on automate.py
> +                self.logger.info('Initial commit pushed to main branch.')
working on.

2023-09-27 16:02 UTC, RanaTayyab commented on automate.py
> +import github
defined as:

GitPython==3.1.36
PyGithub==1.59.1

2023-09-27 16:03 UTC, RanaTayyab commented on automate.py
> +from github import Github
thanks both! @stacybrock @tsoliangwu0130

2023-09-28 00:15 UTC, RanaTayyab commented on automate.py
> +                self.logger.info('Initial commit pushed to main branch.')
done.

2023-09-28 15:04 UTC, tsoliangwu0130 approved these changes
Left a minor comment but approved. Feel free to merge after addressing it.

2023-09-28 15:04 UTC, tsoliangwu0130 commented on automate.py
> +                 repo_name: str, repo_dir: str):
For consistency, can you break them individually as you did for other functions? https://github.com/osu-mist/github-testing-automation/pull/1/commits/9e5492c7ddaaa85a6ce3fbc7c812785eafde9cc0#diff-fe4e7ea6dd494968f4823f696e85b509be6725e750c93e8e07b5ad850024e506R145-R151

2023-09-28 18:44 UTC, RanaTayyab commented
done with changes

2023-09-28 18:44 UTC, merged